spring.application.name=microservicio-seguridad
server.port=8181

spring.mongodb.uri=mongodb+srv://lauracardona43736_db_user:PJoD2I1d1V0aFsAW@cluster0.6zvdelq.mongodb.net/?appName=Cluster0
spring.mongodb.database=db_seguridad

jwt.secret=aaa
jwt.expiration=3600000
